---
# Metadata for the common role

galaxy_info:
  author: Herman Wong
  description: Common prerequisites and system configuration for Kafka cluster nodes
  company: ""
  license: Apache-2.0
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - kafka
    - zookeeper
    - system
    - configuration
    - prerequisites

dependencies: []
