---
# Metadata for the java role

galaxy_info:
  author: Herman Wong
  description: OpenJDK installation for Kafka and ZooKeeper
  company: ""
  license: Apache-2.0
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - java
    - openjdk
    - jdk
    - kafka
    - zookeeper

dependencies: []
