---
# Handlers for the zookeeper role

- name: Restart zookeeper
  ansible.builtin.systemd:
    name: "{{ zookeeper_service_name }}"
    state: restarted
    daemon_reload: true
  listen: restart zookeeper

- name: Reload zookeeper
  ansible.builtin.systemd:
    name: "{{ zookeeper_service_name }}"
    state: reloaded
  listen: reload zookeeper

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
